### ISSUE TITLE
Question: embedded etch sign registration required

### ISSUE THREAD

**Issue by ap-justin** [anvilco/node-anvil#340]
After creating sign URL with `generateEtchSignUrl`,
visiting the URL in the page requires `signer` to login 
<img width="1342" alt="image" src="https://github.com/anvilco/node-anvil/assets/89639563/bbaf0eca-b530-4af4-8b80-277b95a719de">

is it possible, that `signer` only sign and no need to register account with anvil ?

**Comment by newhouse** [comment]
Hi there @ap-justin and thanks for using the Anvil API client for Node!

I'm going to guess that the `signer` in question is linked to an e-mail address that is associated with a User in our system? Probably you? Unfortunately, right now, if that's the case then the User will be required to log in in order to perform the action.

The good news is that this is probably very unlikely in a real-world scenario, and is probably due to you testing things out. A random Signer in your flow probably won't have an account with us, and would not have this experience.

Maybe try changing the signer email in your testing to some other email (like  personal one, or add a `+anvil` to it, etc) and see if that works without a login then?

**Comment by ap-justin** [comment]
> in question is linked to an e-mail address that is associated with a User in our system? Probably you? Unfortunately, right now, if that's the case then the User will be required to log in in order to perform the action.

It's weird,  but before, I tried to paste generated link on another browser and got directed to login page - but my recent tries, there's no more login 🤔

> A random Signer in your flow probably won't have an account with us, and would not have this experience.
Recent tries doesn't redirect me to login page 👍

at the end of the day, seems like everything is working just fine 🤞
thanks for your response ser @newhouse
