### ISSUE TITLE
Remove Demo message

### ISSUE THREAD

**Issue by x9nico** [anvilco/node-anvil#365]
## Expected Behavior
No message.

## Actual Behavior
Demo message.
Any ideas how to remove it?

![image](https://github.com/anvilco/node-anvil/assets/8091015/6845d77b-94b0-4331-9951-0f609aec893b)

**Comment by newhouse** [comment]
Hi there @x9nico and thanks for using Anvil's node client!

Those messages are added usually for 1 of 2 reasons:
- The API Key you are using is your `development` key.
- You are passing `true` for the `isTest`/`test` (or similar) arguments to the calls you are making.

These exist so that you can develop your solutions without being "charged" by Anvil for the calls made when using those keys or arguments.

I suspect that the culprit is the API key in your case, but that's just a guess. We recommend developing with your Dev key, and then when you're making real production calls you use your Prod API key.

Let me know if that explains and solves things, or if you need any more help.

**Comment by newhouse** [comment]
Going to close this for now...let us know if you have any more problems/questions
